package it.ltc.bartolini.model.costanti;

public enum ChiusuraGiacenza {
	
	_000("ANCORA IN GIACENZA"),
	_001("MERCE RICONSEGNATA AL DESTINATARIO"),
	_002("MERCE RITORNATA AL MITTENTE"),
	_003("MERCE RICONSEGNATA AL DESTINATARIO SENZA C/ASSEGNO"),
	_004("MERCE SVINCOLATA DAL DESTINATARIO C/O NS.MAGAZZINO"),
	_005("MERCE RICONSEGNATA AL DESTINATARIO IN PORTO FRANCO"),
	_006("MERCE DIROTTATA AD ALTRO INDIRIZZO"),
	_007("MERCE RITIRATA DAL RAPPRESENTANTE"),
	_008("MERCE RICONSEGNATA AL DESTINATARIO IN P.F. SENZA C/ASSEGNO"),
	_009("VEDI PRATICA FURTO"),
	_010("MERCE RICONSEGNATA AL DESTINATARIO CON C/ASSEGNO RIDOTTO"),
	_011("MERCE DISTRUTTA SU DISPOSIZIONI DEL MITTENTE"),
	_012("MERCE A GIAC/SEDE PER DANNO PER ERRATA GEST. GIACENZE"),
	_013("MERCE A GIAC/SEDE PER SCADUTI TERMINI CONSERV. BAM"),
	_014("MERCE DISTRUTTA PER CALAMITA' NATURALI"),
	_015("CHIUSURA PER APERTURA C.A.");

	private final String descrizione;
	
	private ChiusuraGiacenza(String descrizione) {
		this.descrizione = descrizione;
	}
	
	@Override
	public String toString() {
		return descrizione;
	}
	
}
